### PR TITLE
cosmetic changes in login form style

### PR DESCRIPTION
**Pull request by wojtekagh**
cosmetic one :) added some margins to login panel to give labels, inputs and button some air :)
loginpanel

### CODE REVIEW

**Comment by pchaigno** [comment]
With which web browser did you test it?

**Comment by wojtekagh** [comment]
Firefox and Chrome - I believe margins, padding and cursor option will be properly rendered in every browser :) cursor:hand and cursor:pointer is for MacOS and others :)

**Comment by pchaigno** [comment]
> I believe margins, padding and cursor option will be properly rendered in every browser :) cursor:hand and cursor:pointer is for MacOS and others :)

It should but with IE you never know... Any way to test with IE on your end?

**Comment by wojtekagh** [comment]
now is also tested in IE 5+ :) I have windows with IE 11 and developers tools with old version emulators :)

**Comment by pchaigno** [comment]
Awesome!

**Pull request merged**
