### PR TITLE
Add travis ci

### PR DESCRIPTION
**Pull request by tapasweni-pathak**
Added a concrete travis.yml file which sets up the platform for testing, a7044ae.

<del>How should I test this?</del>
I tested, it is working fine for one test case that @northdpole pushed. [Here](https://travis-ci.org/tapasweni-pathak/hackademic/jobs/78332494) is the success log. :smile: 

Let me know if I need to add something.

Please merge my previous PR first then this, as this is based on the fix_codesniffer_warnings branch, that will help me to avoid fixing merging issues. :) The changes that are coming are from previous PR. They will automatically go after the previous one is merged.

### CODE REVIEW

**Comment by pchaigno** [comment]
@tapasweni-pathak I just merged your second PR. Could you update the present one?

**Comment by tapasweni-pathak** [comment]
This can be merged. @northdpole @pchaigno

**Comment by pchaigno** [comment]
@northdpole Could you enable Travis CI for Hackademic?

**Comment by northdpole** [comment]
I will, gimme until the weekend, I'm a bit swamped this week.
(Unless you can give it a go :) )

**Comment by pchaigno** [comment]
> (Unless you can give it a go :) )

Access to the Hackademic account is required to enable Travis CI ;)

**Pull request merged**
