### PR TITLE
added test cases for start, stop, info

### PR DESCRIPTION
**Pull request by mebjas**
TODO
 - [x] Implement vagrant dns thing left
 - [x] Create example challenge
 - [x] Method to allocate unique private IP to box
 - [x] Parse `config.inc.php` to get information on current domain

### CODE REVIEW

**Comment by mebjas** [comment]
Here's a question, what should we use to make sure we assign a unique private IP to the created box?

 - File based solution: maintain list of used IPs and allocate one
 - Use DB for this?

**Comment by northdpole** [comment]
for now just generate a random ip in the local subnet and bridge it to the host ip via the vagrantfile settings

**Comment by mebjas** [comment]
no but if multiple boxes are up we need to make sure new one is assigned a unique one

**Comment by northdpole** [comment]
so first one gets a random one, second one gets the firsts + 1 third first +2 etc. We don't expect more than 5-10 vms running per host in any case

**Comment by mebjas** [comment]
In that case we can simply keep this info in memory and pick one.

Cool would implement so!

----------------------------------------------------------------------------
Kind Regards,
Minhaz | My Projects <http://cistoner.org/projects> | M
<http://cistoner.org/minhaz/>y blog <http://blog.minhazav.me/>

**Pull request merged**
