### PR TITLE
141 ranking bug - handle equal ranking score

### PR DESCRIPTION
**Pull request by wojtekagh**
missing part of the #141 issue (The user who solves a challenge first should be ranked before another who solved the same after him. )

Because ranking is not about one challenge, but about summary, I've made it by checking last successful attempt to any challenge. So if two users have the same score, the user who has finished earlier has better ranking :)

### CODE REVIEW

**Comment by pchaigno** [comment]
Looks :+1: to me!
@northdpole Can I get a second pair of :eyes: on this?

**Comment by pchaigno** [comment]
@wojtekagh Could you also add unit tests for this?

**Comment by wojtekagh** [comment]
Unfortunatelly, I don't have skills to make unit tests :(

**Comment by pchaigno** [comment]
What do you mean?

**Comment by wojtekagh** [comment]
I've never prepared unit test before. That's the problem.

**Comment by pchaigno** [comment]
Oh okay. It's not a big change so I'll merge this as is.
If you can add unit tests in the future that'd be awesome!

**Pull request merged**
