### PR TITLE
Caesar-Polybius-Vigenere

### PR DESCRIPTION
**Pull request by merrodah**

### CODE REVIEW

**Comment by pchaigno** [comment]
Is this work in progress? If not, could you describe what it does?

**Comment by northdpole** [comment]
@merrodah  is commiting his implementation of some basic crypto algorithms in php. This is part of his bsc thesis. His advisor has already contacted us and asked if we're interested in using his code.

@pchaigno  I suggest we move it in a testing branch and we verify that it runs fine with hackademic first (and make the necessary changes if it doesn't) , what do you think?

**Comment by pchaigno** [comment]
@northdpole How/Where are we going to use this?

> @pchaigno I suggest we move it in a testing branch and we verify that it runs fine with hackademic first (and make the necessary changes if it doesn't) , what do you think?

:+1:

**Comment by northdpole** [comment]
@pchaigno sorry, jsut noticed that they are not challenges but crypto calculators/implementations, we can put them in a "teaching material" branch  in case ppl want to use them as articles or sth. (Or we can just scrap them).

**Comment by pchaigno** [comment]
Maybe @merrodah had an idea for implementing a challenge?

**Comment by northdpole** [comment]
As far as I understood @merrodah is just trying to graduate. So I 
wouldn't be surprised if he doesn't want to make it a full challenge.
For me that's fine, we can make do with what he gave us.

**Comment by northdpole** [comment]
merged in branch merodah-ciphers

**Pull request closed without merging**
