### PR TITLE
Code to start and stop a challenge implemented

### PR DESCRIPTION
**Pull request by mebjas**
Tasks Done:
- [x] Code to start, stop a challenege
- [x] Unit test for create a challenge option

Todos for this pull:
- [ ] create a subdomain for each challenege started, considering to use https://github.com/acostamosaicgroup/vagrant-hostmaster
- [x] Verify every files in case of create a challeneg
- [x] detailed Unit test for start challenge
- [ ] Unit test for stop challenege

### CODE REVIEW

**Comment by mebjas** [comment]
@northdpole so we go with https://github.com/acostamosaicgroup/vagrant-hostmaster for managing /etc/hosts records?

**Comment by mebjas** [comment]
implemented code to get info about vagrant boxes / challenges. They can be called in 4 categories
`info all box`
`info all challenge`
`info box <box id>`
`info challenge <challenge id>`

and json response have data like:
`no of active challenges`, `box id`, `base box`, `last updated`

TODO: 
 -[ ] unit testing for `start challenge`
 -[ ] unit testing for `info` commands

**Comment by northdpole** [comment]
excellent! Great work @mebjas.

When can you have the unit tests ready?

**Comment by northdpole** [comment]
@pchaigno  can you take a look and give an opinion when you have time?

**Comment by pchaigno** [comment]
@northdpole I'll look into this on Tuesday.

**Comment by mebjas** [comment]
Ill write the unittest in 2to 3 daya.
same for hosts

**Pull request merged**
